### ISSUE TITLE
About date and time

### ISSUE THREAD

**Issue by russel89** [coolboii/cbnBase#1]
Hey there,

First question: How can i change the little date and time box that display before the contents (in archive page) to just a plain text like Posted it on (show date) and it would display right next to the amount of comments.

Second question: How do I show the post info in single article?

**Comment by coolboiime** [comment]
I believe to achieve the first question, this is the code you're looking for:
```html+php
<span class="link">
    <span class="icon" data-icon="&#xE807;" aria-hidden="true"></span>
    <a href="<?php the_permalink(); ?>" title="<?php the_title(); ?>">
        <?php echo __( 'Posted on', 'cbn-base' ) . ' ' . get_the_date(); ?>
    </a>
</span>
```

For the second question, you can copy the code from the ```archive.php``` file and paste it directly into the ```single.php``` file. It's recommended to place the information at the bottom of the content as to not interfere with the social buttons.
